#pragma once

#include "NativeGameplayTags.h"

namespace MyUITags
{
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Store_Inventory);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Store_Progression);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Store_Battle);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Store_PlayerVitals);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Store_SurvivorHUD);

	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Event_LevelUp);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Event_ShowToast);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Event_RarePickup);

	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Request_Open_LevelUpDialog);
	HOYOGAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Request_Show_RarePickupToast);
}
